services:
  api:
    image: ghcr.io/malakel87/task-manager-api:prod
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/tasksdb

  db:
    image: mongo:6
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

  # Lab 5 final
  